'use strict';

/**
 * TOTP two-factor authentication (RFC 6238).
 *
 * Real implementation, not a placeholder:
 *   - secrets are generated by otplib and stored AES-256-GCM encrypted,
 *     so a database dump alone does not yield working second factors
 *   - the enrolment secret is only trusted once a code proves the user
 *     actually scanned it, which stops anyone locking themselves out
 *   - a one-step clock window is allowed, covering normal device drift
 *     without meaningfully widening the guessing window
 *   - backup codes are bcrypt-hashed and single-use
 *
 * The QR code is rendered from an otpauth:// URI by the browser, so no
 * secret is ever sent to a third-party QR service.
 */

const bcrypt = require('bcrypt');
const { authenticator } = require('otplib');
const QRCode = require('qrcode');

const db = require('../config/database');
const logger = require('../utils/logger');
const { encrypt, decrypt, randomBackupCode } = require('../utils/crypto');
const { ValidationError } = require('../utils/errors');

// One step either side of the current 30s window.
authenticator.options = { window: 1, step: 30 };

const BACKUP_CODE_COUNT = 10;
const BCRYPT_ROUNDS = 10;

async function getStatus(userId) {
  const row = await db.queryOne(
    'SELECT is_enabled, confirmed_at, last_used_at FROM user_2fa WHERE user_id = ?',
    [userId],
  );

  const remainingCodes = row?.is_enabled
    ? Number(await db.queryValue(
      'SELECT COUNT(*) AS total FROM user_2fa_backup_codes WHERE user_id = ? AND used_at IS NULL',
      [userId],
    ))
    : 0;

  return {
    enrolled: Boolean(row),
    enabled: Boolean(row?.is_enabled),
    confirmedAt: row?.confirmed_at || null,
    lastUsedAt: row?.last_used_at || null,
    remainingCodes,
  };
}

function isEnabled(userId) {
  return db.queryValue(
    'SELECT is_enabled FROM user_2fa WHERE user_id = ? AND is_enabled = 1', [userId],
  ).then((value) => Boolean(value));
}

/**
 * Starts enrolment: generates a secret and returns the otpauth URI plus
 * a QR code. The secret is stored but NOT enabled until a code confirms
 * it, so a half-finished setup can never lock anyone out.
 *
 * The QR is rendered here into a data: URI rather than pointing an
 * <img> at a QR-generating web service, which would hand the shared
 * secret to a third party.
 *
 * @returns {Promise<{secret: string, uri: string, qr: string}>}
 */
async function beginEnrolment(user, issuer = 'Portfolio CMS') {
  const secret = authenticator.generateSecret();
  const uri = authenticator.keyuri(user.email, issuer, secret);

  await db.query(
    `INSERT INTO user_2fa (user_id, secret_encrypted, is_enabled)
     VALUES (?, ?, 0)
     ON DUPLICATE KEY UPDATE secret_encrypted = VALUES(secret_encrypted), is_enabled = 0, confirmed_at = NULL`,
    [user.id, encrypt(secret)],
  );

  const qr = await QRCode.toDataURL(uri, {
    margin: 1,
    width: 200,
    errorCorrectionLevel: 'M',
    color: { dark: '#121212', light: '#ffffff' },
  });

  logger.security('2fa: enrolment started', { userId: user.id });
  return { secret, uri, qr };
}

/**
 * Confirms enrolment with a code from the authenticator app, enabling
 * 2FA and issuing backup codes.
 *
 * @returns {Promise<string[]>} the plaintext backup codes - shown once
 */
async function confirmEnrolment(userId, token) {
  const row = await db.queryOne('SELECT secret_encrypted FROM user_2fa WHERE user_id = ?', [userId]);
  if (!row) throw new ValidationError('Start the setup again - no pending enrolment was found.');

  const secret = decrypt(row.secret_encrypted);

  if (!authenticator.check(String(token || '').replace(/\s/g, ''), secret)) {
    logger.security('2fa: enrolment code rejected', { userId });
    throw new ValidationError('That code was not correct. Check your authenticator app and try again.');
  }

  const codes = Array.from({ length: BACKUP_CODE_COUNT }, () => randomBackupCode());

  await db.transaction(async (connection) => {
    await connection.execute(
      'UPDATE user_2fa SET is_enabled = 1, confirmed_at = NOW() WHERE user_id = ?', [userId],
    );
    await connection.execute('DELETE FROM user_2fa_backup_codes WHERE user_id = ?', [userId]);

    for (const code of codes) {
      await connection.execute(
        'INSERT INTO user_2fa_backup_codes (user_id, code_hash) VALUES (?, ?)',
        [userId, await bcrypt.hash(code, BCRYPT_ROUNDS)],
      );
    }
  });

  logger.security('2fa: enabled', { userId });
  return codes;
}

/**
 * Verifies a code at sign-in. Accepts either a TOTP code or an unused
 * backup code.
 *
 * @returns {Promise<{ok: boolean, usedBackupCode?: boolean}>}
 */
async function verify(userId, token) {
  const cleaned = String(token || '').replace(/[\s-]/g, '');
  if (!cleaned) return { ok: false };

  const row = await db.queryOne(
    'SELECT secret_encrypted FROM user_2fa WHERE user_id = ? AND is_enabled = 1', [userId],
  );
  if (!row) return { ok: false };

  // ---- TOTP
  try {
    if (authenticator.check(cleaned, decrypt(row.secret_encrypted))) {
      await db.query('UPDATE user_2fa SET last_used_at = NOW() WHERE user_id = ?', [userId]);
      return { ok: true, usedBackupCode: false };
    }
  } catch (err) {
    logger.error('2fa: could not verify token', { userId, message: err.message });
    return { ok: false };
  }

  // ---- backup code, single use
  const candidates = await db.query(
    'SELECT id, code_hash FROM user_2fa_backup_codes WHERE user_id = ? AND used_at IS NULL',
    [userId],
  );

  for (const candidate of candidates) {
    // The stored hash covers the formatted code, so compare both forms.
    const matches = await bcrypt.compare(cleaned, candidate.code_hash)
      || await bcrypt.compare(`${cleaned.slice(0, 4)}-${cleaned.slice(4)}`, candidate.code_hash);

    if (matches) {
      await db.query('UPDATE user_2fa_backup_codes SET used_at = NOW() WHERE id = ?', [candidate.id]);
      await db.query('UPDATE user_2fa SET last_used_at = NOW() WHERE user_id = ?', [userId]);
      logger.security('2fa: backup code used', { userId, remaining: candidates.length - 1 });
      return { ok: true, usedBackupCode: true };
    }
  }

  logger.security('2fa: verification failed', { userId });
  return { ok: false };
}

/** Turns 2FA off and discards the secret and backup codes. */
async function disable(userId) {
  await db.transaction(async (connection) => {
    await connection.execute('DELETE FROM user_2fa_backup_codes WHERE user_id = ?', [userId]);
    await connection.execute('DELETE FROM user_2fa WHERE user_id = ?', [userId]);
  });

  logger.security('2fa: disabled', { userId });
}

/** Issues a fresh set of backup codes, invalidating the old ones. */
async function regenerateBackupCodes(userId) {
  const enabled = await isEnabled(userId);
  if (!enabled) throw new ValidationError('Two-factor authentication is not enabled.');

  const codes = Array.from({ length: BACKUP_CODE_COUNT }, () => randomBackupCode());

  await db.transaction(async (connection) => {
    await connection.execute('DELETE FROM user_2fa_backup_codes WHERE user_id = ?', [userId]);
    for (const code of codes) {
      await connection.execute(
        'INSERT INTO user_2fa_backup_codes (user_id, code_hash) VALUES (?, ?)',
        [userId, await bcrypt.hash(code, BCRYPT_ROUNDS)],
      );
    }
  });

  logger.security('2fa: backup codes regenerated', { userId });
  return codes;
}

module.exports = {
  getStatus,
  isEnabled,
  beginEnrolment,
  confirmEnrolment,
  verify,
  disable,
  regenerateBackupCodes,
  BACKUP_CODE_COUNT,
};
